set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'Valloric/YouCompleteMe'
Plugin 'octol/vim-cpp-enhanced-highlight'
" Plugin 'w0ng/vim-hybrid'
" Plugin 'morhetz/gruvbox'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
syntax on
set number
set laststatus=2
let g:c_no_curly_error = 1 " do not tag {} as error in ()
let g:cpp_class_scope_highlight = 1 " for vim-ccp-enhanced-highlight
let g:airline_powerline_fonts = 1
let g:airline#extensions#whitespace#enabled = 0
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_tab_nr = 0
let g:airline#extensions#tabline#show_buffers = 1
let g:airline#extensions#tabline#close_symbol = ''
let g:airline_theme = 'powerlineish'
" change airline symbols
if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
" no diagnostic information
let g:ycm_enable_diagnostic_signs = 0
" which filetype should turned on
let g:ycm_filetype_whitelist = { 	
	\ 'cpp': 1,
	\ 'c': 1
	\}
" set to 99, so identifier completion engine will not be triggered just 
" leaves semantic engine. default is 2.
" let g:ycm_min_num_of_chars_for_completion = 99
set completeopt=menuone
set tabstop=8		"use tab which 8 spaces long
set shiftwidth=8
set noexpandtab
set cindent 		"c-style indent
set hlsearch 		"highlight search
set wrapscan 		"when to the bottom,then back to top
set incsearch 		"use increment search
set showcmd 		"show cmd you entered
set ruler
set cursorline
set hidden 		"hidden buffer already gone

" setup colorscheme
"set background=dark
colorscheme mongolia_dark
"set cursorline if seted every window will hight cursor line at the same time
"set cursorcolumn
hi CursorLine   cterm=NONE ctermbg=black ctermfg=NONE 
" hi CursorColumn cterm=NONE ctermbg=darkred ctermfg=white 
hi VertSplit cterm=NONE ctermbg=NONE ctermfg=white
hi StatusLineNC cterm=NONE ctermbg=darkblue ctermfg=darkred
hi StatusLine cterm=NONE ctermbg=white ctermfg=black
hi Pmenu cterm=NONE ctermbg=8 ctermfg=7
hi PmenuSel cterm=NONE ctermbg=white ctermfg=black
hi PmenuThumb cterm=NONE ctermbg=darkgreen ctermfg=grey
hi Visual cterm=NONE ctermbg=darkyellow ctermfg=black


"  different filetype different indentation
" autocmd Filetype c,h setlocal noexpandtab tabstop=8 shiftwidth=8
" autocmd Filetype cc,hh setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2
autocmd BufNewFile,BufRead *.c,*.h setlocal noexpandtab tabstop=8 shiftwidth=8
autocmd BufNewFile,BufRead *.cc,*.hh setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2


" set different ycm_extra_conf.py for c and c++ source files
" typically it should be let b:variable, but here is a exception.
autocmd BufNewFile,BufRead *.c,*.h let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf_c.py'
autocmd BufNewFile,BufRead *.cc,*.hh let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf_cc.py'

"map some useful keys
"include no highlight search(not perminant turnoff)
	nmap .xs :nohlsearch<CR>
"map keys of window operation
	"map basic window movement keys
		nmap .k <C-W>k
		nmap .j <C-W>j
		nmap .h <C-W>h
		nmap .l <C-W>l
	"map keys of opening and closing a window
	 	nmap .s :split<CR>
		nmap .v :vsplit<CR>
		nmap .n :new<CR>
		nmap [n :vnew<CR>
	"map keys of chosing a window
		nmap .t <C-W>t
		nmap .b <C-W>b
		nmap [p <C-W>p
	"map key of exchanging two windows
		nmap .x <C-W>x
"map key of openning nerdtree
	nmap .2 :NERDTree<CR>
"map key of openning tagbar
	nmap .3 :TagbarToggle<CR>
"map key of openning taglist
	"nmap \3 :TlistToggle<CR>
"map hotkey of omnicppcomplation, use this to generate tags file 
	map <C-F11> :!ctags -R  --c++-kinds=+pl --fields=+iaS --extra=+q .<CR>
"map key of changing cursorline
	"map ,c :setlocal cursorline<CR>
	"map ,d :setlocal nocursorline<CR>
	


" Open a new buffer
" <leader> is "\" by default
nmap <leader>t :enew<CR> 
" Next buffer
nmap <leader>l :bnext<CR>
" Previous buffer
nmap <leader>h :bprevious<CR>
" Delete buffer
nmap <leader>d :bdelete<CR>


"map of Alternate Header file plugin a.vim
nmap ,s :AS<CR>
nmap ,v :AV<CR>
nmap ,a :A<CR>
nmap ,w :IHV<CR>
nmap ,e :IHS<CR>
nmap ,r :IH<CR>


"map of hex edit-function
nmap ,g :%!xxd -r<CR>
nmap ,h :%!xxd<CR>
