#!/bin/bash

####################################################
#
# This is the config file for herbstluftwm
# 
####################################################

# define hc as "alias" of herbstclient for
#+less typing
# shopt -s expand_aliases will make bash expand
#+aliases.

#shopt -s expand_aliases
#alias hc='herbstclient'

hc() {
	herbstclient "$@"
}

# "reload" hook should be emitted in the first line of autostart file.
#+all daemons will quit and autostart file is reloaded

hc emit_hook reload


# remove all key bindings

hc keyunbind --all


# define modifier

Mod=Mod1


# define tags (use array)

TAG_NAMES=( term web img herb null foo )
TAG_KEYS=( {1..6} 0 )
hc rename default "${TAG_NAMES[0]}" || true


# bind keystork to specific tags
#+and add tags

for i in ${!TAG_NAMES[@]} ; do 
	hc add "${TAG_NAMES[$i]}"
	key="${TAG_KEYS[$i]}"
	if ! [ -z "$key" ] ; then
		hc keybind "$Mod-$key" use_index "$i"
		hc keybind "$Mod-Shift-$key" move_index "$i"
	fi
done


# spawn different programs

hc keybind $Mod-m spawn dmenu_run -dim 0.6 -fn -gohu-gohufont-medium-r-normal--14-100-100-100-c-80-iso10646-1 -h 14 -l 16 -w 200 -sb '#823232'	# spawn menu
hc keybind $Mod-w spawn dwb		# spawn web browser
hc keybind $Mod-p spawn gimp		# spawn picture editor
hc keybind Control-Shift-Return spawn urxvt	# spawn terminal


# wm management stuff

hc keybind Control-Shift-q quit 	# quit herbstluft
hc keybind Control-Shift-r reload	# reload autostart file
hc keybind $Mod-c close			# close focused window


# focusing clients

hc keybind $Mod-h focus left		# focus left client
hc keybind $Mod-l focus right		# focus right client
hc keybind $Mod-j focus down 		# focus down client
hc keybind $Mod-k focus up		# focus up client


# moving clients

hc keybind $Mod-Shift-h shift left	# move client to the left 
hc keybind $Mod-Shift-l shift right	# move client to the right
hc keybind $Mod-Shift-k shift up	# move client to the up
hc keybind $Mod-Shift-j shift down 	# move client to the down


# splitting frames

hc keybind Super-h split left    0.5	# split focused frame in subframes
hc keybind Super-l split right   0.5	# split focused frame in subframes
hc keybind Super-j split bottom	 0.5	# split focused frame in subframes
hc keybind Super-k split top	 0.5	# split focused frame in subframes
hc keybind Super-e split explode


# resizing frames

resizestep=0.01
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep


# cycle through tags

hc keybind $Mod-comma use_index +1 --skip-visible
hc keybind $Mod-period use_index -1 --skip-visible


# layouting

hc keybind $Mod-r remove 
hc keybind $Mod-Control-Tab cycle_layout 1
hc keybind Super-f floating toggle
hc keybind Super-m fullscreen toggle
hc keybind Super-p pseudotile toggle


# focus

hc keybind Control-period cycle_monitor
hc keybind Super-c cycle
hc keybind $Mod-u jumpto urgent


# colors

hc set frame_border_active_color '#212121'
hc set frame_border_normal_color '#212121'
hc set frame_bg_active_color '#f05050'
hc set frame_bg_normal_color '#212121'
hc set window_border_active_color '#BA5050'
hc set window_border_normal_color '#212121'
hc set window_border_urgent_color '#00FFFF'


# window & frame settings

hc set window_border_width 1
hc set window_border_inner_width 0
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_gap 0
hc set frame_bg_transparent 1
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0


# rules

hc unrule -F
hc rule focus=on
hc rule class=Dwb tag=term focus=on
hc rule class=mpv tag=term focus=on


# unlock

hc unlock


herbstclient set tree_style '╾│ ├└╼─┐'


hc detect_monitors

panel=~/.config/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
	"$panel" &
done


